### PR TITLE
Make Blob have "$type" field when serialized

### PR DESCRIPTION
**Pull request by Emplexx**
When you serialize a blob
```
val blob = Blob.StandardBlob(BlobRef(""), "", 0)
val serialized = json.encodeToJsonElement(blob)
println(serialized)
```
it prints `{"ref":{"$link":""},"mimeType":"","size":0}`. As you can see, there is no `"$type":"blob"` field, which makes it impossible to make a post with an image for example (it fails with the following error: `{"error":"InvalidRequest","message":"Invalid app.bsky.feed.post record: Record/embed/images/0/image should be a blob ref"}`)

`@SerialName("blob")` annotation on the sealed interface seems to have no effect because of the custom `BlobSerializer` serializer being used, so the workaround I found is to add a property inside the class annotated with [`@EncodeDefault`](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-encode-default/) which forces it to serialize the property

Then the code above prints: `{"ref":{"$link":""},"mimeType":"","size":0,"$type":"blob"}`

### CODE REVIEW

**Comment by christiandeange** [comment]
> the workaround I found is to add a property inside the class

Sounds reasonable. Just to make sure, does this still work with deserializing a `Blob` coming from the API? My worry is that removing the `@SerialName("blob")` annotation from the class itself might prevent that from being the case.

**Comment by Emplexx** [comment]
I just tried it with a blob from a real API response, and it works 

From my understanding, `@SerialName("blob")` is not applied appropriately, because with polymorphism `@SerialName` describes names of sub-classes rather than the parent class. I could be wrong about this but that is what the [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md) suggests, in all examples the annotation is applied to sub-classes

However, leaving the class annotated doesn't affect serialization so it could just be left as before, the annotation doesn't have to be removed

**Comment by christiandeange** [comment]
@Emplexx I think you're just missing an import in here, otherwise everything LGTM

**Comment by Emplexx** [comment]
My apologies, I didn't realise

**Comment by christiandeange** [comment]
@Emplexx I think there's an (intentional) API difference that was introduced and is now failing in the PR build, if you run `./gradlew apiDump` that should update the expected API dump

**Pull request merged**
