### PR TITLE
Introduce `AuthenticatedXrpcBlueskyApi` convenience implementation

### LINKED ISSUE #11: Include mechanic similar to "XrpcAuthPlugin" in bluesky library
Thank you for working on this library! This was exactly what I was searching for.

Playing around with the library a little I really missed a class similar to `XrcpAuthPlugin` in the main library. Most devs will probably copy the plugin or rewrite a quite similar one.

Thanks!

### PR DESCRIPTION
**Pull request by christiandeange**
This implementation will transparently manage the active session and refresh tokens for that BlueskyApi instance as it interacts with session-related APIs.

cc @CanYumusak this should resolve #11 – let me know how it looks for you!

### CODE REVIEW

**Comment by JayOhEn** [comment]
I was actually looking for something like this, will update my lib version once it's available. Thank you!

**Comment by Jon6193** [comment]
Can this be merged and released in a new version? I'm trying to avoid making these changes locally to use this new class for session management instead

**Review by CanYumusak — APPROVED** [review]

**Comment by CanYumusak** [comment]
I'm not sure if @christiandeange  is waiting for me, but I've given my approval. I won't be able to test it in-depth until after the holiday season but it generally looks good

**Comment by christiandeange** [comment]
> I'm not sure if @christiandeange is waiting for me, but I've given my approval. I won't be able to test it in-depth until after the holiday season but it generally looks good

Just wanted to get external opinion(s) on the API design here. Thanks all! It'll be included in a new release shortly.

**Pull request merged**
